[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
marketplace = "DZEGM4VV5uoLyQaQ9HS638yTdkGVgpxvGUdCNP81qpbx"

[provider]
cluster = "devnet"
wallet = "./deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
